name: flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_osm_plugin: ^0.53.1
  http: ^0.13.5
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/