// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2iEIgVxKA-fiJG7UuDJD88GP-bgxv6k',
    appId: '1:747566974872:web:ca536601ab99b1e4fe8ded',
    messagingSenderId: '747566974872',
    projectId: 'map-app-5c35c',
    authDomain: 'map-app-5c35c.firebaseapp.com',
    storageBucket: 'map-app-5c35c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD87NhRt-pp4jmpEJXKFMJVNauR_3AcODI',
    appId: '1:747566974872:android:28524c8f9091244efe8ded',
    messagingSenderId: '747566974872',
    projectId: 'map-app-5c35c',
    storageBucket: 'map-app-5c35c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbwMtjFoU0PrFaxo3B0G1j13UXLQ9uDEU',
    appId: '1:747566974872:ios:e8cf6049a9ab9c3bfe8ded',
    messagingSenderId: '747566974872',
    projectId: 'map-app-5c35c',
    storageBucket: 'map-app-5c35c.appspot.com',
    iosClientId: '747566974872-aj1p5k6vkhrgu8l2h0q4364s9gt8pelo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbwMtjFoU0PrFaxo3B0G1j13UXLQ9uDEU',
    appId: '1:747566974872:ios:e8cf6049a9ab9c3bfe8ded',
    messagingSenderId: '747566974872',
    projectId: 'map-app-5c35c',
    storageBucket: 'map-app-5c35c.appspot.com',
    iosClientId: '747566974872-aj1p5k6vkhrgu8l2h0q4364s9gt8pelo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
